export default {
  EDUOK_SCHOOL_MANAGEMENT_SYSTEM: 'EduOK School Management System',
  INNOVATION_OF_Education_System: 'Innovation of Education System',
  SCHOOL_MANAGEMENT: 'School Management',
  REPORT_AND_PRINTABLE: 'Report and Printable',
  SCHOOL_PROFILE: 'School Profile',
  SETTINGS: 'Settings',
  REVENUE: 'Revenue',
  STAFF: 'Staff',
  MANAGE: 'Manage',
  USER_MATRIX: 'User Matrix',
  SECURITY: 'Security',
  PRIVILEGE: 'Privilege',
  LEAVE: 'Leave',
  SUGGETION_AND_FEEDBACK: 'Suggetion and Feedback',
  SETTLEMENT: 'Settlement',
  ADMIN: 'Admin',
  MY_ACCOUNT: 'My Account',
  OFFER_ZONE: 'Offer Zone',
  EDUOK_PRODUCT: 'EduOK Products',
};
