export const GET_ADMIN_MAIN_DASHBOARD = 'GET_ADMIN_MAIN_DASHBOARD';
export const SET_ADMIN_MAIN_DASHBOARD = 'SET_ADMIN_MAIN_DASHBOARD';
export const GET_CLASS_WITH_STUDENT_COUNT = 'GET_CLASS_WITH_STUDENT_COUNT';
export const SET_CLASS_WITH_STUDENT_COUNT = 'SET_CLASS_WITH_STUDENT_COUNT';

export const UPDATE_CLASS_NAME_SUCCESS = 'UPDATE_CLASS_NAME_SUCCESS';
export const UPDATE_CLASS_NAME_FAILURE = 'UPDATE_CLASS_NAME_FAILURE';
